### ISSUE TITLE
wait deprecated (@testing-library/react@11.2.5)

### ISSUE THREAD

**Issue by JoaoCapoAlm** [rocketseat-education/bootcamp-gostack-apps#5]
No teste da página de SignIn ao tentar importar o wait da @testing-library/react aparece esse aviso a baixo. Na aula não tem nenhum comentário sobre isso. Eu substitui pelo waitFor

```shel
@deprecated
wait has been deprecated and replaced by waitFor instead.
In most cases you should be able to find/replace wait with waitFor.
Learn more:
https://testing-library.com/docs/dom-testing-library/api-async#waitfor.
```

**Comment by jpedroschmitz** [comment]
Na última versão da `@testing-library/react` eles substituíram para `waitFor`, por isso o warning. 
Da forma que você fez vai dar certo!
